name: pysdm

on: [push]

jobs:
  pysdm_1dkid:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialise Conda/Mamba
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: superdrops-in-action
          auto-activate-base: false
          use-mamba: true
          miniforge-version: 'latest'
          conda-remove-defaults: true

      - name: Update Mamba Environment
        run: mamba env update -n superdrops-in-action -f environment.yaml

      - name: Create output directories
        run: |
          mkdir -p ./build/bin
          mkdir -p ./build/figs

      - name: Run PySDM 1dkid
        run: bash ./pysdm_1dkid/bash/run_pysdm_1dkid.sh

      - name: Upload plots
        uses: actions/upload-artifact@v4
        with:
          name: pysdm-results
          path: "*.png"
